server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:  
    maxThreadsForPeerReplication: 0  
    

spring:
  security:
    basic:
      enabled: true
    user:
      name: eureka_user
      password: eureka_pass
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
