spring:
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017/softbank_exame?authSource=admin
  jpa:
    hibernate:
      ddl-auto: auto
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka_user:eureka_pass@localhost:8761/eureka
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  app:
    name: exames 
    description: Micro serviço responsável pelo crud de exames.
logging:
  file: target/exames-logs.log 
server:
  port: ${PORT:0} 
ribbon:
  eureka:
    enabled: true  
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/v1/oauth/usuario 
          

