spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    password: 123456
    url: jdbc:mysql://localhost:3306/softbank_usuario
    username: root 
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    password: 123456
    schemas: softbank_usuario
    url: jdbc:mysql://localhost:3306
    user: root  
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka_user:eureka_pass@localhost:8761/eureka
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}   
info:
  app:
    name: oauth2
    description: Micro serviço responsável pela autenticação e autorização dos outros end points.
logging:
  file: target/logs.log
server:
  port: 8088

oauth2_client: softbank_client
oauth2_secret: softbank_secret

