
package br.com.softbank.consulta.soap;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebServiceClient(name = "ConsultaPortService", targetNamespace = "http://softbank.com.br", wsdlLocation = "http://localhost:8080/ws/consultas.wsdl")
public class ConsultaPortService
    extends Service
{

    private final static URL CONSULTAPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPORTSERVICE_EXCEPTION;
    private final static QName CONSULTAPORTSERVICE_QNAME = new QName("http://softbank.com.br", "ConsultaPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/consultas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPORTSERVICE_WSDL_LOCATION = url;
        CONSULTAPORTSERVICE_EXCEPTION = e;
    }

    public ConsultaPortService() {
        super(__getWsdlLocation(), CONSULTAPORTSERVICE_QNAME);
    }

    public ConsultaPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPORTSERVICE_QNAME, features);
    }

    public ConsultaPortService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPORTSERVICE_QNAME);
    }

    public ConsultaPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPORTSERVICE_QNAME, features);
    }

    public ConsultaPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaPort
     */
    @WebEndpoint(name = "ConsultaPortSoap11")
    public ConsultaPort getConsultaPortSoap11() {
        return super.getPort(new QName("http://softbank.com.br", "ConsultaPortSoap11"), ConsultaPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPort
     */
    @WebEndpoint(name = "ConsultaPortSoap11")
    public ConsultaPort getConsultaPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://softbank.com.br", "ConsultaPortSoap11"), ConsultaPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPORTSERVICE_EXCEPTION!= null) {
            throw CONSULTAPORTSERVICE_EXCEPTION;
        }
        return CONSULTAPORTSERVICE_WSDL_LOCATION;
    }

}
