
package br.com.softbank.consulta.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebService(name = "ConsultaPort", targetNamespace = "http://softbank.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaPort {


    /**
     * 
     * @param salvarConsultaRequest
     * @return
     *     returns br.com.softbank.consulta.soap.SalvarConsultaResponse
     */
    @WebMethod(operationName = "SalvarConsulta")
    @WebResult(name = "SalvarConsultaResponse", targetNamespace = "http://softbank.com.br", partName = "SalvarConsultaResponse")
    public SalvarConsultaResponse salvarConsulta(
        @WebParam(name = "SalvarConsultaRequest", targetNamespace = "http://softbank.com.br", partName = "SalvarConsultaRequest")
        SalvarConsultaRequest salvarConsultaRequest);

    /**
     * 
     * @param findConsultaByFiltersRequest
     * @return
     *     returns br.com.softbank.consulta.soap.FindConsultaByFiltersResponse
     */
    @WebMethod(operationName = "FindConsultaByFilters")
    @WebResult(name = "FindConsultaByFiltersResponse", targetNamespace = "http://softbank.com.br", partName = "FindConsultaByFiltersResponse")
    public FindConsultaByFiltersResponse findConsultaByFilters(
        @WebParam(name = "FindConsultaByFiltersRequest", targetNamespace = "http://softbank.com.br", partName = "FindConsultaByFiltersRequest")
        FindConsultaByFiltersRequest findConsultaByFiltersRequest);

    /**
     * 
     * @param deleteConsultaRequest
     * @return
     *     returns br.com.softbank.consulta.soap.DeleteConsultaResponse
     */
    @WebMethod(operationName = "DeleteConsulta")
    @WebResult(name = "DeleteConsultaResponse", targetNamespace = "http://softbank.com.br", partName = "DeleteConsultaResponse")
    public DeleteConsultaResponse deleteConsulta(
        @WebParam(name = "DeleteConsultaRequest", targetNamespace = "http://softbank.com.br", partName = "DeleteConsultaRequest")
        DeleteConsultaRequest deleteConsultaRequest);

    /**
     * 
     * @param findAllConsultaRequest
     * @return
     *     returns br.com.softbank.consulta.soap.FindAllConsultaResponse
     */
    @WebMethod(operationName = "FindAllConsulta")
    @WebResult(name = "FindAllConsultaResponse", targetNamespace = "http://softbank.com.br", partName = "FindAllConsultaResponse")
    public FindAllConsultaResponse findAllConsulta(
        @WebParam(name = "FindAllConsultaRequest", targetNamespace = "http://softbank.com.br", partName = "FindAllConsultaRequest")
        FindAllConsultaRequest findAllConsultaRequest);

    /**
     * 
     * @param findConsultaByIdRequest
     * @return
     *     returns br.com.softbank.consulta.soap.FindConsultaByIdResponse
     */
    @WebMethod(operationName = "FindConsultaById")
    @WebResult(name = "FindConsultaByIdResponse", targetNamespace = "http://softbank.com.br", partName = "FindConsultaByIdResponse")
    public FindConsultaByIdResponse findConsultaById(
        @WebParam(name = "FindConsultaByIdRequest", targetNamespace = "http://softbank.com.br", partName = "FindConsultaByIdRequest")
        FindConsultaByIdRequest findConsultaByIdRequest);

}
