spring:
  cache:
    type: redis
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    password: 123456
    schemas: softbank_laboratorio
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka_user:eureka_pass@localhost:8761/eureka
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}      
info:
  app:
    name: laboratorios  
    description: Micro serviço responsável pelo crud de laboratórios.
logging:
  file: target/logs.log
server:
  port: ${PORT:0}
ribbon:
  eureka:
    enabled: true   
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/v1/oauth/usuario
