//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 01:09:34 AM BRT 
//


package br.com.softbank.consultawebservice.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.softbank package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.softbank
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindAllConsultaRequest }
     * 
     */
    public FindAllConsultaRequest createFindAllConsultaRequest() {
        return new FindAllConsultaRequest();
    }

    /**
     * Create an instance of {@link FindAllConsultaResponse }
     * 
     */
    public FindAllConsultaResponse createFindAllConsultaResponse() {
        return new FindAllConsultaResponse();
    }

    /**
     * Create an instance of {@link ConsultaResponse }
     * 
     */
    public ConsultaResponse createConsultaResponse() {
        return new ConsultaResponse();
    }

    /**
     * Create an instance of {@link DeleteConsultaRequest }
     * 
     */
    public DeleteConsultaRequest createDeleteConsultaRequest() {
        return new DeleteConsultaRequest();
    }

    /**
     * Create an instance of {@link FindConsultaByIdRequest }
     * 
     */
    public FindConsultaByIdRequest createFindConsultaByIdRequest() {
        return new FindConsultaByIdRequest();
    }

    /**
     * Create an instance of {@link FindConsultaByFiltersResponse }
     * 
     */
    public FindConsultaByFiltersResponse createFindConsultaByFiltersResponse() {
        return new FindConsultaByFiltersResponse();
    }

    /**
     * Create an instance of {@link FindConsultaByIdResponse }
     * 
     */
    public FindConsultaByIdResponse createFindConsultaByIdResponse() {
        return new FindConsultaByIdResponse();
    }

    /**
     * Create an instance of {@link DeleteConsultaResponse }
     * 
     */
    public DeleteConsultaResponse createDeleteConsultaResponse() {
        return new DeleteConsultaResponse();
    }

    /**
     * Create an instance of {@link SalvarConsultaRequest }
     * 
     */
    public SalvarConsultaRequest createSalvarConsultaRequest() {
        return new SalvarConsultaRequest();
    }

    /**
     * Create an instance of {@link ConsultaRequest }
     * 
     */
    public ConsultaRequest createConsultaRequest() {
        return new ConsultaRequest();
    }

    /**
     * Create an instance of {@link SalvarConsultaResponse }
     * 
     */
    public SalvarConsultaResponse createSalvarConsultaResponse() {
        return new SalvarConsultaResponse();
    }

    /**
     * Create an instance of {@link FindConsultaByFiltersRequest }
     * 
     */
    public FindConsultaByFiltersRequest createFindConsultaByFiltersRequest() {
        return new FindConsultaByFiltersRequest();
    }

}
