eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka_user:eureka_pass@localhost:8761/eureka
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}      
info:
  app:
    name: files  
    description: Micro serviço responsável pelo upload de arquivos, possui um end point de Download com os modelos dos arquivos que devem ser enviados para o sftp pelo end point de upload.
logging:
  file: target/logs.log
server:
  port: ${PORT:0}
ribbon:
  eureka:
    enabled: true   
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/v1/oauth/usuario

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

sftp_host: localhost
sftp_port: 2222
sftp_user: admin
sftp_pass_word: admin123
